### ISSUE TITLE
[Suggestion] Please consider moving the contents of pycrumbs.md to README.md

### ISSUE THREAD

**Issue by arjunmayilvaganan** [kirang89/pycrumbs#106]
Why?
Because, people with no knowledge about GitHub and Markdown files can land directly to repository's home from some source and might not know where the content is. Also, it might look better this way.

And, you can link the `contribution.md` and `authors.md`, containing the corresponding information, to the `README.md`.

**Comment by kirang89** [comment]
I don't remember why I wanted to keep it the way it is. That being said, I don't think I have any problems with this setup, so I'll make the changes soon. 

Thank you for making the suggestion! :)

**Comment by kirang89** [comment]
Done 👍
