### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by learnbyexample** [kirang89/pycrumbs#116]
For topic: https://github.com/kirang89/pycrumbs#mobile-development

http://archlinux.me/dusty/2013/06/13/creating-an-application-in-kivy-part-1/ no longer works. With a bit of search, I found http://buchuki.com/index.php/2013/06/13/creating-an-application-in-kivy-part-1/ which I think is the same

**Comment by kirang89** [comment]
Fixed it. Thanks for pointing it out! :)
