### ISSUE TITLE
Inappropiate content in one of the links in API and Web Services.

### ISSUE THREAD

**Issue by SanketDG** [kirang89/pycrumbs#86]
"Python API for various web services" in [API and Web Services](https://github.com/kirang89/pycrumbs/blob/master/pycrumbs.md#api-and-web-services) is redirecting to inappropriate content.

**Comment by burke-martin** [comment]
its the url pythanapi.com... someone screwed up.

**Comment by kirang89** [comment]
It has been removed for now. Thanks for the heads up!
