### ISSUE TITLE
What about Alphabetization?

### ISSUE THREAD

**Issue by switchhax** [kirang89/pycrumbs#95]
I´ve seen that at many other projects. It helps at points like search-ability. What do you think?

**Comment by kirang89** [comment]
I don't quite follow you. Could you provide an example project that uses alphabetization?

**Comment by switchhax** [comment]
One of my favorites and where it´s really necessary:
On [vhf/free-programming-books](https://github.com/vhf/free-programming-books) the `free-programming-books.md`

It improves searchabilty, clarity and structure.

**Comment by kirang89** [comment]
Ah ok. The reason I didn't do that earlier was because I didn't want to make it feel like an indexed guide. I wanted the doc to be considered like a guide on how to learn Python. For example, if we were to aphabhetize, simple and advanced concepts would be mixed up. What do you think ?

**Comment by switchhax** [comment]
It was an idea. Well but the contents-list should be alphabetized. Because then you can find what you want more easily, most of the chapters/topics are manageable for the normal sight, pretty long topics could be alphabetized for better search-ability.
By the way have you looked to the books on the free-programming-books list, you could include some of them in your list.

**Comment by kirang89** [comment]
Thank you for your suggestions! I'll definitely think over this.
